baseURL = "https://angular.fun"
languageCode = "en-us"
title = "Angular Fun"
theme = "pixyll"
contentDir = "content"
layoutDir = "layouts"
enableEmoji = true
publishDir = "docs"
googleAnalytics = "UA-155942506-1"